# Generated by Django 4.0.1 on 2022-01-13 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_email_alter_repetiteur_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='repetiteur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='repetiteur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='repetiteur',
            name='prenom',
        ),
    ]
