# Generated by Django 4.0.1 on 2022-01-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomJour', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Repetiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('sexe', models.CharField(max_length=10)),
                ('dateNais', models.DateField(verbose_name='date de naissance')),
                ('telephone', models.IntegerField()),
                ('ville', models.CharField(max_length=25)),
                ('quartier', models.CharField(max_length=20)),
                ('niveau_etude', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Informations repetiteur',
            },
        ),
    ]
