# Generated by Django 4.0.1 on 2022-01-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_user',
            field=models.CharField(choices=[('Élève', 'Élève'), ('Parent', 'Parent')], default='Élève', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='type_user',
            field=models.CharField(choices=[('Enseignant', 'Enseignant')], default='Enseignant', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='civilité',
            field=models.CharField(choices=[('Monsieur', 'Monsieur'), ('Mademoiselle', 'Mademoiselle'), ('Madame', 'Madame')], default='Monsieur', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='repetiteur',
            name='civilité',
            field=models.CharField(choices=[('Monsieur', 'Monsieur'), ('Mademoiselle', 'Mademoiselle'), ('Madame', 'Madame')], default='Monsieur', max_length=200, null=True),
        ),
    ]
