# Generated by Django 4.0.1 on 2022-01-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='sexe',
        ),
        migrations.AddField(
            model_name='client',
            name='civilité',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme'), ('Mle', 'Mle')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.matiere'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='civilité',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme'), ('Mle', 'Mle')], max_length=100, null=True),
        ),
    ]
