# Generated by Django 4.0.1 on 2022-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_client_sexe_remove_enseignant_sexe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='coursCli',
            field=models.ManyToManyField(to='core.Cours'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='classeEns',
            field=models.ManyToManyField(to='core.Classe'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matiereEns',
            field=models.ManyToManyField(to='core.Matiere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='classeMat',
            field=models.ManyToManyField(to='core.Classe'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='civilité',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme'), ('Mle', 'Mle')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='titre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='civilité',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme'), ('Mle', 'Mle')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='niveauEtude',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='quartier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='ville',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='intitulé',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
