# Generated by Django 4.0.1 on 2022-01-13 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_client_email_remove_client_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.CharField(default='1H', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeureDebut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.CharField(default='7H', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='lundi', max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cours',
            name='heure',
        ),
        migrations.RemoveField(
            model_name='repetiteur',
            name='listCours',
        ),
        migrations.AddField(
            model_name='cours',
            name='repetiteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.repetiteur'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='duree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.duree'),
        ),
        migrations.AddField(
            model_name='cours',
            name='heure_début',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.heuredebut'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='jour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jour'),
        ),
    ]
