# Generated by Django 4.0.1 on 2022-01-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_courscli_enseignant_classeens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='photoProfil',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
