# Generated by Django 4.0.1 on 2022-01-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_duree_heuredebut_jour_remove_cours_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='duree',
            field=models.CharField(choices=[('1H', '1H'), ('1H30', '1H30'), ('2H', '2H'), ('2H30', '2H30'), ('3H', '3H')], default='2H', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='heure_début',
            field=models.CharField(choices=[('7H', '7H'), ('8H', '8H'), ('9H', '9H'), ('10H', '10H'), ('11H', '11H'), ('12H', '12H'), ('13H', '13H'), ('14H', '14H'), ('15H', '15H'), ('16H', '16H'), ('17H', '17H'), ('18H', '18H')], default='7H', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='jour',
            field=models.CharField(choices=[('lundi', 'lundi'), ('mardi', 'mardi'), ('mercredi', 'mercredi'), ('jeudi', 'jeudi'), ('vendredi', 'vendredi'), ('samedi', 'samedi'), ('dimanche', 'dimanche')], default='lundi', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Duree',
        ),
        migrations.DeleteModel(
            name='HeureDebut',
        ),
        migrations.DeleteModel(
            name='Jour',
        ),
    ]
