# Generated by Django 4.0.1 on 2022-01-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enseignant_photoprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.matiere'),
        ),
    ]
