# Generated by Django 4.0.1 on 2022-01-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cours_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.IntegerField(null=True),
        ),
    ]
