# Generated by Django 4.0.1 on 2022-01-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cours_duree_alter_cours_heure_début_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='langue',
            field=models.CharField(choices=[('fançais', 'fançais'), ('anglais', 'anglais'), ('bilingue', 'bilingue')], default='fançais', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='langue',
            field=models.CharField(choices=[('fançais', 'fançais'), ('anglais', 'anglais'), ('bilingue', 'bilingue')], default='fançais', max_length=200, null=True),
        ),
    ]
