# Generated by Django 4.0.1 on 2022-01-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_enseignant_classeens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='disciplineEns',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='classeEns',
            field=models.ManyToManyField(to='core.Classe'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matiereEns',
            field=models.ManyToManyField(to='core.Matiere'),
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
