# Generated by Django 4.0.1 on 2022-01-07 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_enseignant_disciplineens_enseignant_classeens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='classeEns',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='matiereEns',
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classe')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='disciplineEns',
            field=models.ManyToManyField(to='core.Discipline'),
        ),
    ]
