# Generated by Django 4.0.1 on 2022-01-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_enseignant_classeens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repetiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilité', models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme')], max_length=200, null=True)),
                ('dateNais', models.DateField(null=True)),
                ('niveauEtude', models.CharField(max_length=200, null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('quartier', models.CharField(max_length=200, null=True)),
                ('photoProfil', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='disciplineEns',
        ),
        migrations.RemoveField(
            model_name='client',
            name='civilité',
        ),
        migrations.RemoveField(
            model_name='client',
            name='coursCli',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='classeMat',
        ),
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classe'),
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='listCours',
            field=models.ManyToManyField(to='core.Cours'),
        ),
    ]
