# Generated by Django 4.0.1 on 2022-01-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_repetiteur_remove_enseignant_disciplineens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
