# Generated by Django 4.0.1 on 2022-01-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_client_email_client_nom_client_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='intitulé',
            new_name='intitule',
        ),
    ]
