# Generated by Django 4.0.1 on 2022-01-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cours_heure_cours_jour_alter_repetiteur_photoprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='civilité',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme')], max_length=200, null=True),
        ),
    ]
